### ISSUE TITLE
edit text changes should wait till loses focus before generating action

### ISSUE THREAD

**Issue by fahimk** [vpedak/droidtestrec#12]
great plugin, thanks for building it! Would be nice to wait until loses focus or timer to avoid generating multiple unnecessary lines

```
    // Set text to 'r' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("r"));

    // Set text to 'ri' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("ri"));

    // Set text to 'ric' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("ric"));

    // Set text to 'rich' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("rich"));

    // Set text to 'riche' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("riche"));

    // Set text to 'rich' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("rich"));

    // Set text to 'richa' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("richa"));

    // Set text to 'richar' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("richar"));

    // Set text to 'richard' in DollyEditText with id R.id.edit_text_email
    onView(withId(R.id.edit_text_email)).perform(replaceText("richard"));
```

**Comment by vpedak** [comment]
yes, now I've implemented this by purpose. I can handle event that something is pressed in edit text. But it is not efficient to generate event each time something is pressing, it is better to generate one event to set the whole text when it is finished. and the only way I know to found out is it finished or not is to wait for lose focus. And what do you think is the best way to handle this?

**Comment by fahimk** [comment]
We could add a timeout for when keys stop getting pressed while edit text is focused or when the edit text loses focus.

**Comment by vpedak** [comment]
I think timeout is not an option because user can wait any amount of time before pressing something. So I still can see the only option is to wait for loose focus

**Comment by vpedak** [comment]
Let's keep current implementation yet because I do not see any better way to do this now.
