### ISSUE TITLE
Button-clicking events in AlertDialog are not recorded

### ISSUE THREAD

**Issue by leonard2014** [vpedak/droidtestrec#14]
Buttons like BUTTON_POSITIVE, BUTTON_NEGATIVE, BUTTON_NEUTRAL are not recorded

**Comment by leonard2014** [comment]
Thanks so much! Waiting for the next release now...

**Comment by vpedak** [comment]
New version (0.9.2) is uploaded to plugins repository. The issue should be fixed. Please verify that it is working now for you when you will have time.

**Comment by leonard2014** [comment]
Yes, the clicking events in AlertDialog are recorded perfectly in the new version. Awesome!
