### ISSUE TITLE
Error while Installing APK

### ISSUE THREAD

**Issue by kapil-kapri** [vpedak/droidtestrec#15]
Showing error
The APK file /Users/.../app/build/outputs/apk/app-debug-androidTest-unaligned.apk does not exist on disk.

**Comment by vpedak** [comment]
It looks like there was an error creating test module that is started when recording is started. You should have more information in the log view in Android Studio. Can you please take a look and provide more info what was the root cause?

**Comment by kapil-kapri** [comment]
@LargeTest
public class AndrTestRec extends ActivityInstrumentationTestCase2<AppHomeActivity> {
    public AndrTestRec() {
       super(AppHomeActivity.class);
    }
    private Activity activity;
    @Override
    public void setUp() throws Exception {
        super.setUp();
        activity = getActivity();
    }
    public void testRun() throws InterruptedException {
        new ActivityListener(getInstrumentation(), activity, 1457688642494L).start();
        Thread.sleep(24_60_60*1000);
    }
}

Getting an error :
java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=co.go.fynd.debug/co.go.fynd.activity.AppHomeActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1457688912786 and now the last time the queue went idle was: 1457688912786. If these numbers are the same your activity might be hogging the event queue.
at android.support.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:362)
at android.test.InstrumentationTestCase.launchActivityWithIntent(InstrumentationTestCase.java:119)
at android.test.InstrumentationTestCase.launchActivity(InstrumentationTestCase.java:97)
at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:104)
at co.go.fynd.activity.AndrTestRec.setUp(AndrTestRec.java:19)
at junit.framework.TestCase.runBare(TestCase.java:132)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:240)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1944)

**Comment by kapil-kapri** [comment]
How to handle network calls cases ..???

**Comment by vpedak** [comment]
It looks like this is a problem inside Android instrumentation :( I found out that some people has the same issue - https://github.com/googlesamples/android-testing/issues/56

The workaround is to exclude  appcompat and support-v4 in your gradle config file

```
androidTestCompile ('com.android.support.test.espresso:espresso-contrib:2.2'){
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
}

```

And regarding the network calls. Espresso has special [IdlingResource](http://developer.android.com/reference/android/support/test/espresso/IdlingResource.html) interface  that you can implement to notify Espresso when network call is finished . You can take a look at example [here](http://stackoverflow.com/questions/30733718/how-to-use-espresso-idling-resource-for-network-calls).

But as easy solution/workaround you can enable "Generate delays between actions as it was recorded" checkbox and generated sources will use delays as it was recorded. The generated code will also use IdlingResource as described here - http://droidtestlab.com/delay.html

**Comment by vpedak** [comment]
Hi @kapilkapri007 , was you able to resolve this?

**Comment by kapil-kapri** [comment]
Still issue is not resolve , i am already using : 

```
androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.2.1') {
    // Necessary to avoid version conflicts
    exclude group: 'com.android.support', module: 'appcompat'
    exclude group: 'com.android.support', module: 'support-v4'
    exclude group: 'com.android.support', module: 'support-annotations'
    exclude module: 'recyclerview-v7'
}
```

**Comment by lhoracek** [comment]
I'm having the same issue right now ..

```
Testing started at 17:17 ...

04/07 17:17:52: Launching TestRecorderTemporary1460042223642
$ adb push /xxx/app/build/outputs/apk/app-uk-debug.apk /data/local/tmp/xxx.uk.debug
$ adb shell pm install -r "/data/local/tmp/xxx.uk.debug"
    pkg: /data/local/tmp/xxx.uk.debug
Success

The APK file /xxx/app/build/outputs/apk/app-uk-debug-androidTest-unaligned.apk does not exist on disk.
Error while Installing APK
```

There is no such file in the outputs directory so it looks like assembleAndroidTest was not invoked or did not finish before running the testing suit.
When I run assembleAndroidTest or checkConnected from console manually recording worked just fine.

**Comment by vpedak** [comment]
@lhoracek I am using AndroidStudio Test Run Configuration to start recording, I just created it on the fly, so I still think that this is issue of test framework itself. 

Take a look please at https://github.com/googlesamples/android-testing/issues/56 they are discussing the same issue and there is an issue create in android itself for this - https://code.google.com/p/android/issues/detail?id=192497 and there is a workaround https://github.com/googlecodelabs/android-testing/blob/master/app/build.gradle#L96 Is it possible for you to try  it?

**Comment by lhoracek** [comment]
@vpedak Calling assembleAndroidTest is workaround for me. Answering the first problem. @kapilkapri007  asked 3 different questions :-)

Excluding libraries is not solution for this apk missing problem as I already use this excluding script in my app a still have this problem with installing androidTest apk. Problem is, that assembleTestAndroid is not called so no androidTest apk exists in outputs directory.

**Comment by vpedak** [comment]
@lhoracek I've upload new version of plugin to the site - http://droidtestlab.com/AndroidTestsRecorder.zip There is a new feature. If you open File > Settings menu, you can find "Android Test Recorder" configuration under "Other Settings". There is a checkbox "leave Run Configuration used for recording". If you will check it plugin will save RunConfiguration that is used to start recording in the list of your run configurations (each time when you click Record button).

So after clicking Record button you are receiving the error. So you will have ability to select this run configuration and start it again. Also you will be able to take a look at it, maybe you will find something wrong... 

Just do not click Stop button because this will remove temporary java class that is using in recording.

So maybe you will have ability to take a look (if you will have time) at this configuration and start it from Studio itself, because I am not sure what is wrong there. This will be just usual Test Run Configuration that must generate all necessary staff itself.

**Comment by nareninindia** [comment]
Setting up run configuration seems to bypass this issue.

**Comment by vpedak** [comment]
@nareninindia Can you please clarify what did to bypass the issue? Are you turn on feature to save Run Configurations and then you started this configuration manually? Or you did something else?

**Comment by nareninindia** [comment]
Steps I followed:
1. Setup Espresso in Android Studio project by adding dependencies to build.gradle.
2. Install Android Tests Recorder from Android Studio plugins repository.
3. Click 'Edit Configurations' -> Select 'Android Tests' -> Press + for creating new configuration.
4. Give a name to the configuration.
5. Add 'Specific instrumentation runner' as 'android.support.test.runner.AndroidJUnitRunner'.
6. Save.
7. Open Android Tests Recorder in usual manner and click Record.

**Comment by vpedak** [comment]
ok, so the problem is in wrong runner configuration. Thanks, I will update the code and generate this runner automatically

**Comment by vpedak** [comment]
@nareninindia I've uploaded fixed version to the site - http://droidtestlab.com/AndroidTestsRecorder.zip
You can try it (download zip and install plugin from file), now you should be able to start recording without changing of Run Configuration.

Thanks

**Comment by vpedak** [comment]
Also as a workaround you can trigger test APK build by Gradle. To make this you should open Gradle Tool Window (View -> Tool Windows - > Gradle menu items, then find your module in Gradle project tree and click at Tasks/build/assembleAndroidTest). This should generate necessary test APK and you will be able to start recording by "Record" button.

**Comment by vpedak** [comment]
new version 0.9.5 with the fix was uploaded to plugins repository

**Comment by m3l3m01t** [comment]
Just open Gradle tool window and refresh all gradle projects
