### ISSUE TITLE
NoClassDefFoundError AndroidTestRunConfigurationType

### ISSUE THREAD

**Issue by rbuiten** [vpedak/droidtestrec#2]
Hello Slava, 

While running the app (at least with the latest version of Android Studio) I will get the following error:  NoClassDefFoundError: org/jetbrains/android/run/testing/AndroidTestRunConfigurationType

It looks like this class is needed by ToolsTestsRecorderAction. Which plugin do I have to download? I couldn't found it in my project.

Thank you for answering.

**Comment by vpedak** [comment]
Hi,

Can you please specify version of Android Studio that you are using? It
looks like new version of Android Studio has some changes in internal
classes (I am using them to start Test Recorder). I need to know the
version of Android Studio to reproduce this and fix.

Thanks,
Slava

**Comment by rbuiten** [comment]
I am using the latest Dev channel version of Android Studio 1.5 beta. This one has build number #AI-141.2384911. The release date of this version is 29th oktober.

Regards, 
Rick

**Comment by vpedak** [comment]
Hi Rick,

Thank you very mach I will try to reproduce this error and fix it. I will
write you when the fix will be ready.

Regards,
Slava Pedak

**Comment by vpedak** [comment]
Hi,

Issues is fixed, I've uploaded new version to the plugins repository.

Thanks,
Slava
