### ISSUE TITLE
If gradle has 2 'dependencies' nodes, then test recorder gives a dialog to setup Expresso

### ISSUE THREAD

**Issue by nareninindia** [vpedak/droidtestrec#20]
Expresso is already setup.
2nd 'dependencies' node has the dependencies required for Expresso and testing.
We separated this for modularity purposes.
Then we are getting the mentioned error.

Not a severe one. But as per gradle, what we did is legal.

Thanks.

**Comment by vpedak** [comment]
Thanks a lot for submitting this issue. I will take a look soon. Maybe you can also attach your gradle build file?

**Comment by nareninindia** [comment]
Attaching build.gradle files for correct way and wrong way.
[correct_build_gradle.txt](https://github.com/vpedak/droidtestrec/files/229723/correct_build_gradle.txt)
[wrong_build_gradle.txt](https://github.com/vpedak/droidtestrec/files/229724/wrong_build_gradle.txt)

**Comment by vpedak** [comment]
It looks like this is a bug in Android Studio API that my plugin is using :( I've created a bug about this - https://code.google.com/p/android/issues/detail?id=207668

But I am not sure that it will be fixed and fixed soon. So as a workaround you can put dependencies section with Espresso first and have other dependencies as second section. Also as I can see you put all dependencies to one section, this will also works.
