### ISSUE TITLE
it change my build.gradle

### ISSUE THREAD

**Issue by gerpsychosocial** [vpedak/droidtestrec#21]
when i start to record it change my build.gradle so i have to sync project

**Comment by vpedak** [comment]
This is done by purpose. Recording is started a code inside the device and to start it I have to update dependencies and add my own jar there. I do not see any other appropriate way to make this.

**Comment by vpedak** [comment]
In addition, you do not need to sync project yourself after starting recording. It will make this automatically. After pressing stop the dependency will be deleted from build.gradle automatically (and yes, here the project will ask you to sync)
