### ISSUE TITLE
Deletes all dependencies after recording

### ISSUE THREAD

**Issue by bootstraponline** [vpedak/droidtestrec#23]
All the dependencies in my build.gradle file have been deleted using the recording plugin. :(

I thought https://github.com/vpedak/droidtestrec/issues/19 was fixed? Is it not published yet to the Android Studio plugins directory?

**Comment by vpedak** [comment]
Hi,

Can you please send me your gradle build file? Last time (issue #19) problem was that special configuration was used there and Android Studio did not process it right.

**Comment by bootstraponline** [comment]
Unfortunately the app is proprietary and I'm not allowed to share the build file. :(

It'd be really cool to adopt a [nanohttpd](https://github.com/NanoHttpd/nanohttpd) type architecture where the record apk is deployed independently of the app under test. Communication would then happen via HTTP. Hijacking the standard gradle build process is painful.

**Comment by vpedak** [comment]
@bootstraponline but maybe you can post your dependencies section only? Do you have one dependency section or several?

Also about "nanohttpd", communication is not a problem. Problem is to build test apk that has my classes inside. I have to reuse existing Android Studio approach to build it, but maybe I should think how to copy existing gradle build file and use it's copy and not the original file to avoid such problems. I will try this.

**Comment by bootstraponline** [comment]
> @bootstraponline but maybe you can post your dependencies section only? 

No, it's company policy. I didn't make the rules.

> Do you have one dependency section or several?

I have 3 dependency sections:

```
android {     
    dependencies {
      // empty
    }
}

dependencies {
  // compile / androidTestCompile / testCompile deps
}

buildscript {
    dependencies {
      // lots of classpath entries
      classpath 'com.android.tools.build:gradle:2.1.0'
    }
}
```

I think copying the file makes sense.

**Comment by bootstraponline** [comment]
> I have to reuse existing Android Studio approach to build it,

You don't. You could ship a pre-built recorder apk and then have the Android Studio plugin communicate with it via HTTP. The signature on the apk has to match so most commercial recorders will automatically resign the app under test using a default cert.

**Comment by vpedak** [comment]
Thanks for the idea, it looks very interesting. But as I know test apk must have a target and this target should be application id of application you are going to record. So I am not sure how to make pre-built apk in such case.

**Comment by bootstraponline** [comment]
> But as I know test apk must have a target and this target should be application id of application you are going to record. So I am not sure how to make pre-built apk in such case.

It's very simple. Appium and Selendroid do this already. You detect the application id and then dynamically replace the test apk manifest with this id.
- [Example from Selendroid](https://github.com/selendroid/selendroid/blob/b52bafb48cb19fa36e5c3ec35a6964a367d89b7c/selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java#L109)
- [Template Manifest](https://github.com/selendroid/selendroid/blob/b52bafb48cb19fa36e5c3ec35a6964a367d89b7c/selendroid-standalone/AndroidManifestTemplate.xml)
- [Resign code](https://github.com/selendroid/selendroid/blob/b52bafb48cb19fa36e5c3ec35a6964a367d89b7c/selendroid-standalone/src/main/java/io/selendroid/standalone/builder/SelendroidServerBuilder.java#L140)

**Comment by bootstraponline** [comment]
Here's another example from Calabash:
-  [calabash-android-build](https://github.com/calabash/calabash-android/blob/c358a851935a1ab687e0fa348bbee0bd3bce893b/ruby-gem/bin/calabash-android-build.rb#L33)

**Comment by bootstraponline** [comment]
helper jars that appium uses:
- https://github.com/appium/unsign_and_move
- https://github.com/appium/sign

**Comment by vpedak** [comment]
@bootstraponline thank you very much for this information, I was not aware on this approach.

But for now I will fix this by saving gradle config before recording and return it back after not because I do not like your approach, but because Android Studio performing a lot of logic during test start (like validating application and building it if necessary, allowing user to select where to deploy, etc). So I should reuse this in any case to avoid making all this myself. 

But in any case this is important info to know and I will think how I can use this in future.

**Comment by vpedak** [comment]
new version 0.9.5 with the fix was uploaded to plugins repository
