### ISSUE TITLE
invalid path encoding

### ISSUE THREAD

**Issue by jbaginski** [vpedak/droidtestrec#3]
``` groovy
dependencies {
    // ...
    compile files('/Users/janusz/Library/Application%20Support/AndroidStudio1.4/AndroidTestsRecorder/lib/AndroidTestsRecorder.jar')
}
```

after replacing `%20` with space it doesn't recognise the package and the plugin adds it again.

**Comment by jbaginski** [comment]
btw. is it possible to prevent the plugin from reformatting `build.gradle` file?

**Comment by vpedak** [comment]
Hi,

Sorry, but now I did not find the way to preserve format of build.gradle. I
am using API that Android Studio provides to operate with build.gradle file
and it is automatically reformat it.

I am working at this issue with space in the path. I plan to resolve it
tomorrow.

Thanks,
Slava Pedak

**Comment by vpedak** [comment]
Hi,

I've uploaded new version with the fix to plugins repository but it will take some time to verify it. So you can download fixed version of plugin directly from the site http://droidtestlab.com/AndroidTestsRecorder.zip

Thanks,
Slava
