### ISSUE TITLE
PluginException on android studio canary channel (2.0)

### ISSUE THREAD

**Issue by otiasj** [vpedak/droidtestrec#6]
Getting the following error when opening android studio :
3:01:59 PM Plugin Error: Android Tests Recorder threw an uncaught PluginException. Disable Plugin
3:01:59 PM PluginException: cannot create class "com.vpedak.testsrecorder.plugin.actions.ToolsTestsRecorderAction" [Plugin: com.vpedak.testsrecorder.plugin.id]
3:02:29 PM EmptyThrowable: Null child action in group Tools () of class class com.intellij.openapi.actionSystem.DefaultCompactActionGroup, id=vpedak.tools.tests.recorder

**Comment by vpedak** [comment]
HI,

I've tried plugin with Android Studio 2.0 Preview and I did not find such error. Also it looks like this is error inside Studio itself (based at exception that you've provided). Problem is that Tools menu item can not be found inside Studio. Seems something is wrong with your installation.

There was another issue under Android Studio 2.0 Preview and I've fixed it. New version of plugin is in repository, so you can try it one more time.

Thanks,
Slava

**Comment by otiasj** [comment]
Thanks, looking into it 
it seems a problem with the java version differences
