### ISSUE TITLE
Use precompiled APK

### ISSUE THREAD

**Issue by bootstraponline** [vpedak/droidtestrec#7]
The [robotium recorder](http://robotium.com/) is cool because you can just pass an APK and begin recording. The droidtestrec Android Studio plugin appears to require compiling the app before you can record.

Any thoughts on adding an option to specify the precompiled APK?

**Comment by vpedak** [comment]
Yes, I saw this ability in Robotium recorder, and maybe it is possible to add this to my recorder, but I am not sure why this is necessary? My understanding is that this is a plugin to Android Studio that is a development tool and usually developers (maybe QA also) are using it to create tests. Why do you need to use precompiled APK for test recording? Can you please describe this more? If I will understand use case it will be more easy for me to understand the priority of this feature.

Thanks,
Slava

**Comment by bootstraponline** [comment]
Typically QA is provided only an apk and not the app source code. That's
why almost all commercial Android recorders (xamarin, appium, robotium)
have a mode that just requires the apk.

**Comment by vpedak** [comment]
ok, I see now. I will take a look how to make this and implement this feature.

**Comment by vpedak** [comment]
One more question. I am trying to understand this use case. If I will make support of recording from precompiled APK user will have a code from recorder. But this is not a finished test, it will not have verification logic and user will have to add it himself. But how he will deal with test sources when he have only precompiled APK? Is Android Studio support this (that test sources will be in the project with precompiled APK as dependency)? I tried to make this, but did not find a way to make this in Android Studio.

Do you have such experience? Can you please share it?

Thanks,
Slava

**Comment by bootstraponline** [comment]
I know Android Studio has support for test only projects. Here's the Google
blueprint which demos this.
https://github.com/googlesamples/android-testing-templates/tree/f8b39e395975c5deb7acc38537f400636555547a/AndroidTestingBlueprint/module-flavor1-androidTest-only

I don't think Android Studio itself supports executing tests against
precompiled apks. It's possible with spoon though. Given the app apk, you
can provide a test apk and then run the tests.

java -jar spoon.jar --apk app.apk --test-apk test.apk
https://github.com/square/spoon

On Fri, Dec 11, 2015 at 12:11 PM, Vyacheslav Pedak <notifications@github.com

**Comment by vpedak** [comment]
Thanks for the link, but as I can see this is a test only project but is it dependent from project with _sources_. It has the following configuration in gradle:

```
// Set the target app project. The module specified here should contain the production code
// test should run against.
targetProjectPath ':app'
```

So it has a reference to the project with application sources.

Problem is that tests must be compiled with dependency to the application and precompiled APK can not be such dependency (as I know). So even if I will try to make support of recording from APK I am not sure how then users will use those generated sources.

Thanks,
Slava

**Comment by bootstraponline** [comment]
If you delete the source code in :app then `gradle assembleDebug` still works. The test apk is generated in `./module-flavor1-androidTest-only/build/outputs/apk/module-flavor1-androidTest-only-debug.apk` Spoon can then be used to run the tests against a release apk:

```
java -jar spoon-runner-1.2.1-jar-with-dependencies.jar \
    --apk app.apk \
    --test-apk module-flavor1-androidTest-only-debug.apk
```

You're correct that Android Studio doesn't support running the tests like that but spoon is easy enough to use and [integrate with gradle](https://github.com/stanfy/spoon-gradle-plugin). Compiling the tests against a skeleton app with no source works fine in Android Studio.

**Comment by vpedak** [comment]
Thank you a lot. I will investigate this more.

**Comment by vpedak** [comment]
After investigation: Espresso supports only tests that are created from sources only (no black box testing is supported). Yes it is possible to create a library and avoid showing sources to QA but in any case this will be normal Android Studio project with all necessary dependencies so there is no way to create Espresso test from APK only.

Maybe we should return to this idea if we will support UIAutomator (that supports black box testing) but now will not implement this.
