### ISSUE TITLE
NavigationMenu (/Drawer Layout) testing items

### ISSUE THREAD

**Issue by MrBlobby** [vpedak/droidtestrec#9]
So the android.support.design.widget NavigationView is a sidebar you can pull out on Android devices and can inflate with a menu of options (to later add click interaction)

However testing this in espresso can be nightmare and was hoping your test recorder would help me out, to no effect.

The problem is. if you have a longish menu and record the test on a highish resolution emulator, you click the hamburger menu to open the sidebar (fine) then click say option 9 (visible on screen) and generate this skeleton test code:

onView(nthChildOf(withId(R.id.toolbar), 2)).perform(click());
onView(nthChildOf(withId(R.id.design_navigation_view), 9)).perform(click());

Now the problem exists if you later test this espresso skeleton on a smaller resolution emulator (where 9th child of the sidebar is just out of view) apparently these options are not in the hierarchy until scrolled too.(Great navigation support library google?!) But yeah the test fails...

So I don't know if this is an issue with the nthChild matcher you generate, or something you can forsee/fix, but just a heads up. Might have explained this bad but if you need any more clarification let me know.

**Comment by lhoracek** [comment]
The error given by espresso should be that the item is not fully visible. If any View is not more than 90 percent visible, espresso throws an error.
You should always do scrollTo action and then click. In case of recorder, it should generate this code for every AdapterView or in case of support RecyclerView. There are already RecyclerViewActions.
Generating onData viewMatchers would be great improvement when AdapterView or RecyclerView can be detected.

**Comment by vpedak** [comment]
@jrattray13  Thanks a lot for submitting this issue, we did not predict this behavior when generating child matcher. Let us think how to make this better and fix this (yes, maybe we shouild scroll to necessary view)

@lhoracek Thanks for the comments. We are generating "onData" statement for every AdapterView in recorder, so this is working fine and without scroll to. RecyclerView is not supported yet, thank you for pointing this out.  But NavigationView is not AdapterView so this is not working here. I think you are right and we should generate addition scroll to action in recorder to support this. Let us test this and fix.

**Comment by lhoracek** [comment]
@vpedak Last time I had dumped view hierachy from navigation view, it had RecyclerView inside its layout. So supporting RecyclerView will solve you two problems

**Comment by vpedak** [comment]
@lhoracek thanks again for your comments, this is helping me a lot. I found out that navigation view has adapter inside, but it is impossible to use onData for it because NavigationMenuItem class is private but it should be used in onData. There is a bug about this in Espresso - https://code.google.com/p/android/issues/detail?id=187701. So I still think that "scroll to" is right solution. I will implement it soon and test.

**Comment by vpedak** [comment]
Hi all,

I've uploaded new version to Plugins Repository (it is also available at site http://droidtestlab.com/AndroidTestsRecorder.zip).

Now special "scrollToPosition" action will be also generated when you are working with NavigationView. This action will scroll to necessary menu item, so if it is not visible it will become visible (before click at it).

 @jrattray13  Please try it if you will have time and let me know if you have any problems. It should resolve your issue.

Thanks,
Slava

**Comment by MrBlobby** [comment]
Works a charm, cheers :+1:  (Perfect for my small emulator!) Will let you know if I run into any issues. Great test recorder project.

**Comment by lhoracek** [comment]
Works great, but I think using RecyclerViewActions.scrollToPosition would do the trick and would not require defining new action inside the test - cleaner and more readable code.
Or actually using [this action](http://developer.android.com/reference/android/support/test/espresso/contrib/RecyclerViewActions.html#actionOnItemAtPosition%28int, android.support.test.espresso.ViewAction%29) does both things at once

**Comment by vpedak** [comment]
yes, you are right but I was worry that RecyclerViewActions requires addition dependency to android.support.test.espresso.contrib and Studio Project might not have it. So generated test will not be compilable. I am worry that nobody will investigate why it is so and will simple think that Recorder generated something wrong. And I do not want to update project dependencies from Recorder to resolve this automatically. So I've decided to generate my own action. Maybe I should generated a comment that this action can be replaced by RecyclerViewActions
